---
swagger: "2.0"
info:
  description: API for returning remote video list
  version: "1"
  title: PublicSegmentAPI
host: virtserver.swaggerhub.com
basePath: /Quietly-Confident/PublicSegmentAPI/1
schemes:
- https
paths:
  /list_video_segments:
    get:
      tags:
      - Administrator
      - Participant
      summary: Returns a list of all video segments in the library.
      description: Requests a list of all public video segments by a remote user.
      operationId: requestPublicVideoList
      produces:
      - application/json
      parameters: []
      responses:
        "200":
          description: Successfully listed all public video segments in library.
        "400":
          description: Failed to fetch video segment list from library.
definitions: {}
